const fs = require('fs');
const path = require('path');

const value = process.env.LAUNCHDARKLY_CLIENT_SIDE_ID || '';
const content = `// Auto-generated by scripts/inject-ld-id.js - set LAUNCHDARKLY_CLIENT_SIDE_ID when running yarn start / yarn build.
export const LAUNCHDARKLY_CLIENT_SIDE_ID = ${JSON.stringify(value)};
`;

const outPath = path.join(__dirname, '../src/ld-config.ts');
fs.writeFileSync(outPath, content);
