# Sets up Node.js and npm for release workflows.
# This ensures all release jobs use the same Node.js and npm versions.
name: Setup Node.js for Release
description: Installs Node.js and updates npm to the latest version
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24.x
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm
      shell: bash
      # Must be greater than 11.5.1 for OIDC.
      run: npm install -g npm@11.6.2
