import { ItemDescriptor, LDIdentifyOptions } from '@launchdarkly/js-client-sdk-common';

/**
 * Options for the identify method when using the Electron SDK.
 * Extends the base identify options with bootstrap support.
 */
export interface ElectronIdentifyOptions extends LDIdentifyOptions {
  /**
   * The initial set of flags to use until the remote set is retrieved.
   *
   * Bootstrap data can be generated by server SDKs. When bootstrap data is provided the SDK
   * identification operation will complete without waiting for any values from LaunchDarkly and
   * the variation calls can be used immediately.
   *
   * If streaming or polling is configured, a connection will subsequently be established
   * to receive live updates.
   *
   * For more information, see the [SDK Reference Guide](https://docs.launchdarkly.com/sdk/features/bootstrapping#javascript).
   */
  bootstrap?: unknown;

  /**
   * Parsed bootstrap data used to ensure that the bootstrap data is only parsed once during
   * the initialization process.
   *
   * @hidden
   */
  bootstrapParsed?: { [key: string]: ItemDescriptor };
}
