export type {
  InitializerEntry,
  ModeDefinition,
  SynchronizerEntry,
} from '@launchdarkly/js-client-sdk-common';

export type {
  AutoEnvAttributes,
  BasicLogger,
  BasicLoggerOptions,
  EvaluationSeriesContext,
  EvaluationSeriesData,
  Hook,
  HookMetadata,
  IdentifySeriesContext,
  IdentifySeriesData,
  IdentifySeriesResult,
  IdentifySeriesStatus,
  LDContext,
  LDContextCommon,
  LDContextMeta,
  LDContextStrict,
  LDEvaluationDetail,
  LDEvaluationDetailTyped,
  LDEvaluationReason,
  LDFlagSet,
  LDFlagValue,
  LDTimeoutError,
  LDInspection,
  LDLogger,
  LDLogLevel,
  LDMultiKindContext,
  LDSingleKindContext,
  TrackSeriesContext,
  LDPluginBase,
  LDPluginEnvironmentMetadata,
  LDPluginSdkMetadata,
  LDPluginApplicationMetadata,
  LDPluginMetadata,
  LDIdentifyResult,
  LDIdentifySuccess,
  LDIdentifyError,
  LDIdentifyTimeout,
  LDIdentifyShed,
  LDDebugOverride,
  LDWaitForInitializationOptions,
  LDWaitForInitializationResult,
  LDWaitForInitializationComplete,
  LDWaitForInitializationFailed,
  LDWaitForInitializationTimeout,
} from '@launchdarkly/js-client-sdk-common';

/**
 * The subset of FDv2 connection modes supported by the Node.js client SDK.
 */
export type FDv2ConnectionMode = 'streaming' | 'polling' | 'offline';
