import { LDContextCommon, LDSingleKindContext, LDUser } from '@launchdarkly/js-sdk-common';

/**
 * @see {@link LDSingleKindContext}
 *
 * The only difference is that the kind cannot be 'multi' which is reserved for multi-kind contexts.
 * Expect this change to be propogated to the common package in the future.
 *
 * @privateRemarks
 * This is helpful for type narrowing to avoid ambiguity when the kind is 'multi'.
 */
type strictSingleKindContext = Omit<LDSingleKindContext, 'kind' | 'key'> & {
  key: string;
  kind: Exclude<string, 'multi'>;
};

/**
 * An anonymous version of {@link LDSingleKindContext}. This is a valid form for contexts used in a
 * client-side sdk because the key will be generated if missing by the {@link ensureKey} function.
 */
type anonymousSingleKindContext = Omit<LDSingleKindContext, 'key' | 'anonymous' | 'kind'> & {
  key?: string;
  anonymous: true;
  kind: Exclude<string, 'multi'>;
};

/**
 * An anonymous version of {@link LDContextCommon}. This is a valid form for contexts used in a
 * client-side sdk because the key will be generated if missing by the {@link ensureKey} function.
 */
type anonymousLDContextCommon = Omit<LDContextCommon, 'key' | 'anonymous'> & {
  key?: string;
  anonymous: true;
};

/**
 * An anonymous version of {@link LDMultiKindContext}. This is a valid form for contexts used in a
 * client-side sdk because the keys will be generated if missing by the {@link ensureKey} function.
 */
interface multiKindContextWithAnonymous {
  kind: 'multi';
  [kind: string]: 'multi' | anonymousLDContextCommon | LDContextCommon;
}

/**
 * A version of {@link LDContext} that may have anonymous contexts. This is an acceptable form of context to identfy with as
 * the keys will be generated by the SDK via the {@link ensureKey} function if they are missing.
 */
export type LDContextWithAnonymous =
  | multiKindContextWithAnonymous
  | strictSingleKindContext
  | anonymousSingleKindContext
  | LDUser;
