import {
  LDContextCommon,
  LDSingleKindContext as LDSingleKindContextBase,
} from '@launchdarkly/js-sdk-common';

/**
 * A single kind context without a key. When this type of context is used, the key will be generated by the SDK via
 * the {@link ensureKey} function.
 */
type singleKindContextWithoutKey = Omit<LDSingleKindContextBase, 'key'>;

/**
 * A multi kind context without a key. When this type of context is used, the keys will be generated by the SDK via
 * the {@link ensureKey} function.
 */
interface multiKindContextWithoutKey {
  kind: 'multi';
  [kind: string]: 'multi' | LDContextCommon | Omit<LDContextCommon, 'key'>;
}

/**
 * A partial context is a context that is missing a key. This is an acceptable form of context to identfy with as
 * the key will be generated by the SDK via the {@link ensureKey} function.
 */
export type LDContextPartial = singleKindContextWithoutKey | multiKindContextWithoutKey;
