import { LDIdentifyOptions } from '@launchdarkly/js-client-sdk-common';

/**
 * @property shedable - If true, the identify operation will be shedable. This means that if multiple identify operations are done, without
 * waiting for the previous one to complete, then intermediate results will be discarded. When false, identify
 * operations will be queued and completed sequentially.
 *
 * Defaults to true.
 */
export interface BrowserIdentifyOptions extends Omit<LDIdentifyOptions, 'waitForNetworkResults'> {
  /**
   * The signed context key if you are using [Secure Mode]
   * (https://docs.launchdarkly.com/sdk/features/secure-mode#configuring-secure-mode-in-the-javascript-client-side-sdk).
   */
  hash?: string;

  /**
   * The initial set of flags to use until the remote set is retrieved.
   *
   * Bootstrap data can be generated by server SDKs. When bootstrap data is provided the SDK the
   * identification operation will complete without waiting for any values from LaunchDarkly and
   * the variation calls can be used immediately.
   *
   * If streaming is activated, either it is configured to always be used, or is activated
   * via setStreaming, or via the addition of change handlers, then a streaming connection will
   * subsequently be established.
   *
   * For more information, see the [SDK Reference Guide](https://docs.launchdarkly.com/sdk/features/bootstrapping#javascript).
   */
  bootstrap?: unknown;
}
