# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = "A basic example of using the LaunchDarkly SDK for Fastly"
language = "javascript"
manifest_version = 3
name = "LaunchDarkly SDK for Fastly Example"
service_id = ""

[scripts]
build = "yarn build"
post_init = "yarn install"

[local_server]

[local_server.backends]

[local_server.backends.launchdarkly]
url = "https://events.launchdarkly.com"

[local_server.kv_stores]

[[local_server.kv_stores.launchdarkly_local]]
key = "LD-Env-local"
path = "./localData.json"
