# This action publishes docs. The docs must have been build prior.
name: Publish Docs
description: Publish documentation to github pages.
inputs:
  workspace_path:
    description: 'The workspace to publish docs for'
    required: true
runs:
  using: composite
  steps:
    # We put the github pages in another directory.
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        path: gh-pages
        ref: gh-pages
    - name: Publish Docs
      shell: bash
      run: |
        echo "Publishing docs for: $WORKSPACE"
        ./scripts/publish-doc.sh
      env:
        WORKSPACE: ${{ inputs.workspace_path }}
