import { LDContext, LDLogger } from '@launchdarkly/js-sdk-common';

import LDEmitter from '../src/LDEmitter';

describe('LDEmitter', () => {
  const error = { type: 'network', message: 'unreachable' };
  let emitter: LDEmitter;
  let logger: LDLogger;

  beforeEach(() => {
    jest.resetAllMocks();
    logger = {
      debug: jest.fn(),
      info: jest.fn(),
      warn: jest.fn(),
      error: jest.fn(),
    };
    emitter = new LDEmitter(logger);
  });

  test('subscribe and handle', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);
    emitter.emit('error', error);

    expect(errorHandler1).toHaveBeenCalledWith(error);
    expect(errorHandler2).toHaveBeenCalledWith(error);
  });

  test('unsubscribe and handle', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);
    emitter.off('error');
    emitter.emit('error', error);

    expect(errorHandler1).not.toHaveBeenCalled();
    expect(errorHandler2).not.toHaveBeenCalled();
    expect(emitter.listenerCount('error')).toEqual(0);
  });

  test('unsubscribing an event should not affect other events', () => {
    const errorHandler = jest.fn();
    const changeHandler = jest.fn();

    emitter.on('error', errorHandler);
    emitter.on('change', changeHandler);
    emitter.off('error'); // unsubscribe error handler
    emitter.emit('error', error);
    emitter.emit('change');

    // change handler should still be affective
    expect(changeHandler).toHaveBeenCalled();
    expect(errorHandler).not.toHaveBeenCalled();
  });

  test('eventNames', () => {
    const errorHandler1 = jest.fn();
    const changeHandler = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('change', changeHandler);

    expect(emitter.eventNames()).toEqual(['error', 'change']);
  });

  test('listener count', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();
    const changeHandler = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);
    emitter.on('change', changeHandler);

    expect(emitter.listenerCount('error')).toEqual(2);
    expect(emitter.listenerCount('change')).toEqual(1);
  });

  test('on listener with arguments', () => {
    const context = { kind: 'user', key: 'test-user-1' };
    const arg2 = { test: 'test' };
    const onListener = jest.fn((c: LDContext, a2: any) => [c, a2]);

    emitter.on('change', onListener);
    emitter.emit('change', context, arg2);

    expect(onListener).toBeCalledWith(context, arg2);
  });

  test('unsubscribe one of many listeners', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);
    emitter.off('error', errorHandler2);
    emitter.emit('error');

    expect(emitter.listenerCount('error')).toEqual(1);
    expect(errorHandler1).toBeCalled();
    expect(errorHandler2).not.toBeCalled();
  });

  test('unsubscribe all listeners manually', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);

    // intentional duplicate calls to ensure no errors are thrown if the
    // same handler gets removed multiple times
    emitter.off('error', errorHandler1);
    emitter.off('error', errorHandler1);
    emitter.off('error', errorHandler2);
    emitter.emit('error');

    expect(emitter.listenerCount('error')).toEqual(0);
    expect(errorHandler1).not.toBeCalled();
    expect(errorHandler2).not.toBeCalled();
  });

  test('unsubscribe all listeners by event name', () => {
    const errorHandler1 = jest.fn();
    const errorHandler2 = jest.fn();

    emitter.on('error', errorHandler1);
    emitter.on('error', errorHandler2);
    emitter.off('error');
    emitter.emit('error');

    expect(emitter.listenerCount('error')).toEqual(0);
    expect(errorHandler1).not.toBeCalled();
    expect(errorHandler2).not.toBeCalled();
  });

  it('handles errors generated by the callback', () => {
    emitter.on('error', () => {
      throw new Error('toast');
    });
    // Should not have an uncaught exception.
    emitter.emit('error');
    expect(logger.error).toHaveBeenCalledWith(
      'Encountered error invoking handler for "error", detail: "Error: toast"',
    );
  });

  describe('maybeReportError', () => {
    it('emits error to listeners when listeners are registered', () => {
      const errorHandler = jest.fn();
      const context = { kind: 'user', key: 'test-user' };
      const err = new Error('test-error');

      emitter.on('error', errorHandler);
      emitter.maybeReportError(context, err);

      expect(errorHandler).toHaveBeenCalledWith(context, err);
      expect(logger.error).not.toHaveBeenCalled();
    });

    it('logs error when no listeners are registered', () => {
      const context = { kind: 'user', key: 'test-user' };
      const err = new Error('test-error');

      emitter.maybeReportError(context, err);

      expect(logger.error).toHaveBeenCalledWith(expect.stringContaining('test-error'));
    });

    it('suppresses logging when a listener is added after construction', () => {
      const errorHandler = jest.fn();
      const context = { kind: 'user', key: 'test-user' };
      const err = new Error('first-error');

      // First error — no listener, should log
      emitter.maybeReportError(context, err);
      expect(logger.error).toHaveBeenCalledTimes(1);

      // Register a listener
      emitter.on('error', errorHandler);

      // Second error — listener present, should emit not log
      const err2 = new Error('second-error');
      emitter.maybeReportError(context, err2);
      expect(errorHandler).toHaveBeenCalledWith(context, err2);
      expect(logger.error).toHaveBeenCalledTimes(1); // still just the first call
    });

    it('resumes logging when all listeners are removed', () => {
      const errorHandler = jest.fn();
      const context = { kind: 'user', key: 'test-user' };

      emitter.on('error', errorHandler);
      emitter.maybeReportError(context, new Error('emitted'));
      expect(errorHandler).toHaveBeenCalledTimes(1);
      expect(logger.error).not.toHaveBeenCalled();

      emitter.off('error', errorHandler);
      emitter.maybeReportError(context, new Error('logged'));
      expect(errorHandler).toHaveBeenCalledTimes(1); // not called again
      expect(logger.error).toHaveBeenCalledTimes(1);
    });
  });

  it('logs a warning when a non-string event name is provided to on', () => {
    const handler = jest.fn();
    emitter.on(123 as any, handler);
    expect(logger.warn).toHaveBeenCalledWith('Only string event names are supported.');
  });

  it('does not register a listener when a non-string event name is provided to on', () => {
    const handler = jest.fn();
    emitter.on(123 as any, handler);
    expect(emitter.listenerCount(123 as any)).toEqual(0);
    emitter.emit(123 as any);
    expect(handler).not.toHaveBeenCalled();
  });
});
