name: Install npm version
# Used to specify a version of npm that supports --provenance (for node installs < 18.X)
description: Install the latest version of the npm CLI utility. 
inputs:
  npm_version:
    description: 'The version of npm to install'
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: 'Install specified npm version'
      shell: bash
      run: |
        npm install -g npm@${{ inputs.npm_version }}
