name: sdk/cloudflare

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # skip CI for markdown-only changes
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/cloudflare-server-sdk'
          workspace_path: packages/sdk/cloudflare

  build-test-cloudflare-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/cloudflare-example'
          workspace_path: packages/sdk/cloudflare/example
          should_build_docs: false
