# Currently this repository uses the Node.js implementation of the contract
# tests for testing. As more implementations are added, they should be ran
# as well. Additionally the contract test implementation should likely be
# moved to a subdirectory.
name: Contract Tests (Node.js Server)

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Build SDK
        run: |
          yarn workspace focus @launchdarkly/node-server-sdk
          yarn workspaces foreach -ptR --from '@launchdarkly/node-server-sdk' run build

      - name: Run Contract Tests
        run: yarn run contract-tests
    env:
      TEST_HARNESS_PARAMS: "--skip-from=./contract-tests/testharness-suppressions.txt"
    