name: Dependency Scan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate-nodejs-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate SBOM
        uses: launchdarkly/gh-actions/actions/dependency-scan/generate-sbom@a210a815330938287c6816ab44b54684996afd0b # main
        with:
          types: 'nodejs'

  evaluate-policy:
    runs-on: ubuntu-latest
    needs:
      - generate-nodejs-sbom
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Evaluate SBOM Policy
        uses: launchdarkly/gh-actions/actions/dependency-scan/evaluate-policy@a210a815330938287c6816ab44b54684996afd0b # main
        with:
          artifacts-pattern: bom-*
