name: sdk/openfeature-node-server nightly

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-getting-started-example:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
        with:
          node-version: 20
      - uses: ./actions/run-example
        with:
          workspace_name: '@launchdarkly/hello-openfeature-node-server'
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
