name: sdk/openfeature-node-server

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-openfeature-node-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Node versions to run on.
        version: [20, 22]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/openfeature-node-server'
          workspace_path: packages/sdk/openfeature-node-server
      # TODO: Add contract tests

  run-getting-started-example:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
        with:
          node-version: 20
      - uses: ./actions/run-example
        with:
          workspace_name: '@launchdarkly/hello-openfeature-node-server'
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
