name: sdk/openfeature-node-server nightly

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-getting-started-example:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./actions/setup-yarn
        with:
          node-version: 20
      - uses: ./actions/run-example
        with:
          workspace_name: '@launchdarkly/hello-openfeature-node-server'
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
