name: sdk/openfeature-cloudflare-server

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-openfeature-cloudflare-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Node versions to run on. Matches this package's own "engines" field (>=22).
        version: [22]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/openfeature-cloudflare-server'
          workspace_path: packages/sdk/openfeature-cloudflare-server
