name: Package size report.
on:
  workflow_call:
    inputs:
      workspace_name:
        type: string
        description: 'Name, from the package.json, of the package to build/test.'
        required: true
      workspace_path:
        type: string
        description: 'Path to the package to release.'
        required: true

permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI: 0
    steps:
      - name: Setup Yarn
        shell: bash
        run: yarn set version 3.4.1
      - uses: actions/checkout@v4
      - uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d
        with:
          directory: ${{ inputs.workspace_path }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build-with-deps
          package_manager: yarn
