name: sdk/react

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test-react:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Node versions to run on.
        version: [20, 22]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.version }}
          registry-url: 'https://registry.npmjs.org'
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/react-sdk'
          workspace_path: packages/sdk/react

  run-example:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn workspaces focus @internal/react-sdk-example-client-only
      - uses: launchdarkly/gh-actions/actions/release-secrets@bbbbbda684f500766264e7fe327668094ba83d1c
        name: 'Get the client-side SDK key'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/sdk/common/hello-apps/client-key = LAUNCHDARKLY_CLIENT_SIDE_ID'
      - uses: launchdarkly/gh-actions/actions/release-secrets@bbbbbda684f500766264e7fe327668094ba83d1c
        name: 'Get the test feature flag key'
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/sdk/common/hello-apps/boolean-flag-key = LAUNCHDARKLY_FLAG_KEY'
      - name: Build SDK dependencies
        run: yarn workspaces foreach -pR --topological-dev --from '@internal/react-sdk-example-client-only' run build
      - name: Build example app
        run: yarn workspace @internal/react-sdk-example-client-only build
      - name: Install Playwright dependencies
        run: yarn workspace @internal/react-sdk-example-client-only playwright install --with-deps chromium
      - name: Run e2e tests
        run: yarn workspace @internal/react-sdk-example-client-only test

# TODO: Add contract tests
