name: sdk/vue

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./actions/setup-yarn
      - id: shared
        name: Shared CI Steps
        uses: ./actions/ci
        with:
          workspace_name: '@launchdarkly/vue-client-sdk'
          workspace_path: packages/sdk/vue
          should_build_docs: false

  # TODO(scaffold): run-example job arrives when examples/getting-started lands
  # TODO(scaffold): contract-tests job arrives when contract-tests land
